from fonctions.fonction_clear_frame import clear_frame
from tkinter import *
import tkinter.font as tkFont
from création_fenetre_jeu import frameBase
import fonctions.fonction_lancement_menu_combat as jeu
from fonctions.fonction_print_compétences import print_compétences
import fonctions.fonction_ShowCombat as back

def ShowCompétences(user, monstre_actuel, monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement) :
    global frameBase

    clear_frame()
    
    # mise en place du canvas
    canvas_1 = Canvas(frameBase, width=1280, height=720)
    bg = PhotoImage(file="assets/bg.png")
    canvas_1.create_image(0, 0, image=bg, anchor="nw")
    canvas_1.pack()

    font = tkFont.Font(family='Helvetica', size=15)

    labelvie_monstre = Label(frameBase, text="PV : {0}/{1}".format(monstre_PV, monstre_PV_Max), background="#7acbf9", font=font)
    labelvie_monstre.place(x=1000, y=175)

    labelvie_user = Label(frameBase, text="PV : {0}/{1}".format(user_PV, user_PV_Max), background="#7acbf9", font=font)
    labelvie_user.place(x=50, y=175)
    labelvie_monstre = Label(frameBase, text="PM : {0}/{1}".format(user.PM, user_PM_Max), background="#7acbf9", font=font)
    labelvie_monstre.place(x=50, y=250)

    # init des sprites
    sprite_gentil = PhotoImage(file="assets/Jam.gif")
    sprite_mechant = PhotoImage(file="assets/monstres/{0}.png".format(monstre_actuel.sprite_name))
    canvas_1.create_image(250, 500, image=sprite_gentil)
    canvas_1.create_image(1000, 450, image=sprite_mechant)


    liste_compétences_apprises = print_compétences(user.id)
    lenght = len(liste_compétences_apprises)

    if lenght == 0 :
        print("0")
    elif lenght == 1 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
    elif lenght == 2 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
    elif lenght == 3 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
    elif lenght == 4 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
    elif lenght == 5 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
    elif lenght == 6 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
    elif lenght == 7 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
    elif lenght == 8 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
        compétence8 = Button(frameBase, text="{0}".format(liste_compétences_apprises[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[7], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence8.place(x=630, y=670)
    elif lenght == 9 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
        compétence8 = Button(frameBase, text="{0}".format(liste_compétences_apprises[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[7], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence8.place(x=630, y=670)
        compétence9 = Button(frameBase, text="{0}".format(liste_compétences_apprises[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[8], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence9.place(x=830, y=620)
    elif lenght == 10 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
        compétence8 = Button(frameBase, text="{0}".format(liste_compétences_apprises[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[7], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence8.place(x=630, y=670)
        compétence9 = Button(frameBase, text="{0}".format(liste_compétences_apprises[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[8], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence9.place(x=830, y=620)
        compétence10 = Button(frameBase, text="{0}".format(liste_compétences_apprises[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[9], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence10.place(x=830, y=670)
    elif lenght == 11 :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
        compétence8 = Button(frameBase, text="{0}".format(liste_compétences_apprises[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[7], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence8.place(x=630, y=670)
        compétence9 = Button(frameBase, text="{0}".format(liste_compétences_apprises[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[8], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence9.place(x=830, y=620)
        compétence10 = Button(frameBase, text="{0}".format(liste_compétences_apprises[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[9], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence10.place(x=830, y=670)
        compétence11 = Button(frameBase, text="{0}".format(liste_compétences_apprises[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[10], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence11.place(x=1030, y=620)
    else :
        compétence1 = Button(frameBase, text="{0}".format(liste_compétences_apprises[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[0], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence1.place(x=30, y=620)
        compétence2 = Button(frameBase, text="{0}".format(liste_compétences_apprises[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[1], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence2.place(x=30, y=670)
        compétence3 = Button(frameBase, text="{0}".format(liste_compétences_apprises[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[2], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence3.place(x=230, y=620)
        compétence4 = Button(frameBase, text="{0}".format(liste_compétences_apprises[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[3], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence4.place(x=230, y=670)
        compétence5 = Button(frameBase, text="{0}".format(liste_compétences_apprises[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[4], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence5.place(x=430, y=620)
        compétence6 = Button(frameBase, text="{0}".format(liste_compétences_apprises[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[5], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence6.place(x=430, y=670)
        compétence7 = Button(frameBase, text="{0}".format(liste_compétences_apprises[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[6], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence7.place(x=630, y=620)
        compétence8 = Button(frameBase, text="{0}".format(liste_compétences_apprises[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[7], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence8.place(x=630, y=670)
        compétence9 = Button(frameBase, text="{0}".format(liste_compétences_apprises[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[8], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence9.place(x=830, y=620)
        compétence10 = Button(frameBase, text="{0}".format(liste_compétences_apprises[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[9], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence10.place(x=830, y=670)
        compétence11 = Button(frameBase, text="{0}".format(liste_compétences_apprises[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[10], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence11.place(x=1030, y=620)
        compétence12 = Button(frameBase, text="{0}".format(liste_compétences_apprises[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: jeu.combat(user, monstre_actuel, "Compétences", liste_compétences_apprises[11], monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
        compétence12.place(x=1030, y=670)

    retour = Button(frameBase, text="Retour", borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: back.ShowCombat(user, monstre_actuel, monstre_PV, monstre_PV_Max, user_PV, user_PV_Max, user_PM_Max, user_Attaque_base, user_Défense_base, user_Vitesse_base, vérif_equipement), font=font, height=1, width=16)
    retour.place(x=1030, y=30)


    frameBase.mainloop()
