from fonctions.fonction_print_armures import print_armure
from fonctions.fonction_equiper_armure import equiper_armure
from création_fenetre_jeu import frameBase
import tkinter.font as tkFont
from tkinter import *
import fonctions.fonction_ShowMenu as back

def ShowArmures(user) :

    liste_armures = print_armure(user)
    lenght = len(liste_armures)

    font = tkFont.Font(family='Helvetica', size=15)

    if lenght == 0 :
        print("0")
    elif lenght == 1 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
    elif lenght == 2 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
    elif lenght == 3 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
    elif lenght == 4 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
    elif lenght == 5 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
    elif lenght == 6 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
    elif lenght == 7 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
    elif lenght == 8 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
    elif lenght == 9 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
    elif lenght == 10 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
    elif lenght == 11 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
    elif lenght == 12 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
    elif lenght == 13 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
    elif lenght == 14 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
    elif lenght == 15 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
    elif lenght == 16 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
    elif lenght == 17 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
    elif lenght == 18 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
    elif lenght == 19 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
    elif lenght == 20 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
        armure20 = Button(frameBase, text="{0}".format(liste_armures[19].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[19]), font=font, height=1, width=16)
        armure20.place(x=230, y=520)
    elif lenght == 21 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
        armure20 = Button(frameBase, text="{0}".format(liste_armures[19].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[19]), font=font, height=1, width=16)
        armure20.place(x=230, y=520)
        armure21 = Button(frameBase, text="{0}".format(liste_armures[20].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[20]), font=font, height=1, width=16)
        armure21.place(x=430, y=520)
    elif lenght == 22 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
        armure20 = Button(frameBase, text="{0}".format(liste_armures[19].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[19]), font=font, height=1, width=16)
        armure20.place(x=230, y=520)
        armure21 = Button(frameBase, text="{0}".format(liste_armures[20].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[20]), font=font, height=1, width=16)
        armure21.place(x=430, y=520)
        armure22 = Button(frameBase, text="{0}".format(liste_armures[21].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[21]), font=font, height=1, width=16)
        armure22.place(x=630, y=520)
    elif lenght == 23 :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
        armure20 = Button(frameBase, text="{0}".format(liste_armures[19].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[19]), font=font, height=1, width=16)
        armure20.place(x=230, y=520)
        armure21 = Button(frameBase, text="{0}".format(liste_armures[20].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[20]), font=font, height=1, width=16)
        armure21.place(x=430, y=520)
        armure22 = Button(frameBase, text="{0}".format(liste_armures[21].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[21]), font=font, height=1, width=16)
        armure22.place(x=630, y=520)
        armure23 = Button(frameBase, text="{0}".format(liste_armures[22].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[22]), font=font, height=1, width=16)
        armure23.place(x=830, y=520)
    else :
        armure1 = Button(frameBase, text="{0}".format(liste_armures[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[0]), font=font, height=1, width=16)
        armure1.place(x=30, y=620)
        armure2 = Button(frameBase, text="{0}".format(liste_armures[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[1]), font=font, height=1, width=16)
        armure2.place(x=30, y=670)
        armure3 = Button(frameBase, text="{0}".format(liste_armures[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[2]), font=font, height=1, width=16)
        armure3.place(x=230, y=620)
        armure4 = Button(frameBase, text="{0}".format(liste_armures[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[3]), font=font, height=1, width=16)
        armure4.place(x=230, y=670)
        armure5 = Button(frameBase, text="{0}".format(liste_armures[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[4]), font=font, height=1, width=16)
        armure5.place(x=430, y=620)
        armure6 = Button(frameBase, text="{0}".format(liste_armures[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[5]), font=font, height=1, width=16)
        armure6.place(x=430, y=670)
        armure7 = Button(frameBase, text="{0}".format(liste_armures[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[6]), font=font, height=1, width=16)
        armure7.place(x=630, y=620)
        armure8 = Button(frameBase, text="{0}".format(liste_armures[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[7]), font=font, height=1, width=16)
        armure8.place(x=630, y=670)
        armure9 = Button(frameBase, text="{0}".format(liste_armures[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[8]), font=font, height=1, width=16)
        armure9.place(x=830, y=620)
        armure10 = Button(frameBase, text="{0}".format(liste_armures[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[9]), font=font, height=1, width=16)
        armure10.place(x=830, y=670)
        armure11 = Button(frameBase, text="{0}".format(liste_armures[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[10]), font=font, height=1, width=16)
        armure11.place(x=1030, y=620)
        armure12 = Button(frameBase, text="{0}".format(liste_armures[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[11]), font=font, height=1, width=16)
        armure12.place(x=1030, y=670)
        armure13 = Button(frameBase, text="{0}".format(liste_armures[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[12]), font=font, height=1, width=16)
        armure13.place(x=30, y=570)
        armure14 = Button(frameBase, text="{0}".format(liste_armures[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[13]), font=font, height=1, width=16)
        armure14.place(x=230, y=570)
        armure15 = Button(frameBase, text="{0}".format(liste_armures[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[14]), font=font, height=1, width=16)
        armure15.place(x=430, y=570)
        armure16 = Button(frameBase, text="{0}".format(liste_armures[15].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[15]), font=font, height=1, width=16)
        armure16.place(x=630, y=570)
        armure17 = Button(frameBase, text="{0}".format(liste_armures[16].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[16]), font=font, height=1, width=16)
        armure17.place(x=830, y=570)
        armure18 = Button(frameBase, text="{0}".format(liste_armures[17].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[17]), font=font, height=1, width=16)
        armure18.place(x=1030, y=570)
        armure19 = Button(frameBase, text="{0}".format(liste_armures[18].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[18]), font=font, height=1, width=16)
        armure19.place(x=30, y=520)
        armure20 = Button(frameBase, text="{0}".format(liste_armures[19].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[19]), font=font, height=1, width=16)
        armure20.place(x=230, y=520)
        armure21 = Button(frameBase, text="{0}".format(liste_armures[20].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[20]), font=font, height=1, width=16)
        armure21.place(x=430, y=520)
        armure22 = Button(frameBase, text="{0}".format(liste_armures[21].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[21]), font=font, height=1, width=16)
        armure22.place(x=630, y=520)
        armure23 = Button(frameBase, text="{0}".format(liste_armures[22].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[22]), font=font, height=1, width=16)
        armure23.place(x=830, y=520)
        armure24 = Button(frameBase, text="{0}".format(liste_armures[23].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_armure(user, liste_armures[23]), font=font, height=1, width=16)
        armure24.place(x=1030, y=520)

    retour = Button(frameBase, text="Retour", borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: back.ShowMenu(user), font=font, height=1, width=16)
    retour.place(x=1030, y=30)


    frameBase.mainloop()

