from fonctions.fonction_clear_frame import clear_frame
from tkinter import *
import tkinter.font as tkFont
from création_fenetre_jeu import frameBase
from fonctions.fonction_print_objets import print_objets

def VoirInventaire(user) :

    clear_frame()

    # mise en place du canvas
    canvas_1 = Canvas(frameBase, width=1280, height=720)
    bg = PhotoImage(file="assets/bg.png")
    canvas_1.create_image(0, 0, image=bg, anchor="nw")
    canvas_1.pack()
    font = tkFont.Font(family='Helvetica', size=15)

    liste_objets_inventaire = print_objets(user.id)
    lenght = len(liste_objets_inventaire)

    if lenght == 0 :
        print("0")
    elif lenght == 1 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
    elif lenght == 2 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)

    elif lenght == 3 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)

    elif lenght == 4 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)

    elif lenght == 5 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)

    elif lenght == 6 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)

    elif lenght == 7 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)

    elif lenght == 8 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)
        objet8 = Label(frameBase, text="{0}".format(liste_objets_inventaire[7].nom), background="#7acbf9", font=font)
        objet8.place(x=630, y=670)

    elif lenght == 9 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)
        objet8 = Label(frameBase, text="{0}".format(liste_objets_inventaire[7].nom), background="#7acbf9", font=font)
        objet8.place(x=630, y=670)
        objet9 = Label(frameBase, text="{0}".format(liste_objets_inventaire[8].nom), background="#7acbf9", font=font)
        objet9.place(x=830, y=620)

    elif lenght == 10 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)
        objet8 = Label(frameBase, text="{0}".format(liste_objets_inventaire[7].nom), background="#7acbf9", font=font)
        objet8.place(x=630, y=670)
        objet9 = Label(frameBase, text="{0}".format(liste_objets_inventaire[8].nom), background="#7acbf9", font=font)
        objet9.place(x=830, y=620)
        objet10 = Label(frameBase, text="{0}".format(liste_objets_inventaire[9].nom), background="#7acbf9", font=font)
        objet10.place(x=830, y=670)

    elif lenght == 11 :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)
        objet8 = Label(frameBase, text="{0}".format(liste_objets_inventaire[7].nom), background="#7acbf9", font=font)
        objet8.place(x=630, y=670)
        objet9 = Label(frameBase, text="{0}".format(liste_objets_inventaire[8].nom), background="#7acbf9", font=font)
        objet9.place(x=830, y=620)
        objet10 = Label(frameBase, text="{0}".format(liste_objets_inventaire[9].nom), background="#7acbf9", font=font)
        objet10.place(x=830, y=670)
        objet11 = Label(frameBase, text="{0}".format(liste_objets_inventaire[10].nom), background="#7acbf9", font=font)
        objet11.place(x=1030, y=620)

    else :
        objet1 = Label(frameBase, text="{0}".format(liste_objets_inventaire[0].nom), background="#7acbf9", font=font)
        objet1.place(x=30, y=620)
        objet2 = Label(frameBase, text="{0}".format(liste_objets_inventaire[1].nom), background="#7acbf9", font=font)
        objet2.place(x=30, y=670)
        objet3 = Label(frameBase, text="{0}".format(liste_objets_inventaire[2].nom), background="#7acbf9", font=font)
        objet3.place(x=230, y=620)
        objet4 = Label(frameBase, text="{0}".format(liste_objets_inventaire[3].nom), background="#7acbf9", font=font)
        objet4.place(x=230, y=670)
        objet5 = Label(frameBase, text="{0}".format(liste_objets_inventaire[4].nom), background="#7acbf9", font=font)
        objet5.place(x=430, y=620)
        objet6 = Label(frameBase, text="{0}".format(liste_objets_inventaire[5].nom), background="#7acbf9", font=font)
        objet6.place(x=430, y=670)
        objet7 = Label(frameBase, text="{0}".format(liste_objets_inventaire[6].nom), background="#7acbf9", font=font)
        objet7.place(x=630, y=620)
        objet8 = Label(frameBase, text="{0}".format(liste_objets_inventaire[7].nom), background="#7acbf9", font=font)
        objet8.place(x=630, y=670)
        objet9 = Label(frameBase, text="{0}".format(liste_objets_inventaire[8].nom), background="#7acbf9", font=font)
        objet9.place(x=830, y=620)
        objet10 = Label(frameBase, text="{0}".format(liste_objets_inventaire[9].nom), background="#7acbf9", font=font)
        objet10.place(x=830, y=670)
        objet11 = Label(frameBase, text="{0}".format(liste_objets_inventaire[10].nom), background="#7acbf9", font=font)
        objet11.place(x=1030, y=620)
        objet12 = Label(frameBase, text="{0}".format(liste_objets_inventaire[11].nom), background="#7acbf9", font=font)
        objet12.place(x=1030, y=670)

    frameBase.mainloop()


