from fonctions.fonction_print_arme import print_arme
from fonctions.fonction_equiper_arme import equiper_arme
from création_fenetre_jeu import frameBase
import tkinter.font as tkFont
from tkinter import *


def ShowArmes(user) :
    
    liste_armes = print_arme(user)
    lenght = len(liste_armes)

    font = tkFont.Font(family='Helvetica', size=15)

    if lenght == 0 :
        print("0")
    elif lenght == 1 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
    elif lenght == 2 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
    elif lenght == 3 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
    elif lenght == 4 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
    elif lenght == 5 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
    elif lenght == 6 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
    elif lenght == 7 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
    elif lenght == 8 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
    elif lenght == 9 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
    elif lenght == 10 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
    elif lenght == 11 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
        arme11 = Button(frameBase, text="{0}".format(liste_armes[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[10].id), font=font, height=1, width=16)
        arme11.place(x=1030, y=620)
    elif lenght == 12 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
        arme11 = Button(frameBase, text="{0}".format(liste_armes[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[10].id), font=font, height=1, width=16)
        arme11.place(x=1030, y=620)
        arme12 = Button(frameBase, text="{0}".format(liste_armes[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[11].id), font=font, height=1, width=16)
        arme12.place(x=1030, y=670)
    elif lenght == 13 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
        arme11 = Button(frameBase, text="{0}".format(liste_armes[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[10].id), font=font, height=1, width=16)
        arme11.place(x=1030, y=620)
        arme12 = Button(frameBase, text="{0}".format(liste_armes[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[11].id), font=font, height=1, width=16)
        arme12.place(x=1030, y=670)
        arme13 = Button(frameBase, text="{0}".format(liste_armes[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[12].id), font=font, height=1, width=16)
        arme13.place(x=30, y=570)
    elif lenght == 14 :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
        arme11 = Button(frameBase, text="{0}".format(liste_armes[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[10].id), font=font, height=1, width=16)
        arme11.place(x=1030, y=620)
        arme12 = Button(frameBase, text="{0}".format(liste_armes[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[11].id), font=font, height=1, width=16)
        arme12.place(x=1030, y=670)
        arme13 = Button(frameBase, text="{0}".format(liste_armes[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[12].id), font=font, height=1, width=16)
        arme13.place(x=30, y=570)
        arme14 = Button(frameBase, text="{0}".format(liste_armes[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[13].id), font=font, height=1, width=16)
        arme14.place(x=230, y=570)
    else :
        arme1 = Button(frameBase, text="{0}".format(liste_armes[0].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[0].id), font=font, height=1, width=16)
        arme1.place(x=30, y=620)
        arme2 = Button(frameBase, text="{0}".format(liste_armes[1].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[1].id), font=font, height=1, width=16)
        arme2.place(x=30, y=670)
        arme3 = Button(frameBase, text="{0}".format(liste_armes[2].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[2].id), font=font, height=1, width=16)
        arme3.place(x=230, y=620)
        arme4 = Button(frameBase, text="{0}".format(liste_armes[3].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[3].id), font=font, height=1, width=16)
        arme4.place(x=230, y=670)
        arme5 = Button(frameBase, text="{0}".format(liste_armes[4].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[4].id), font=font, height=1, width=16)
        arme5.place(x=430, y=620)
        arme6 = Button(frameBase, text="{0}".format(liste_armes[5].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[5].id), font=font, height=1, width=16)
        arme6.place(x=430, y=670)
        arme7 = Button(frameBase, text="{0}".format(liste_armes[6].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[6].id), font=font, height=1, width=16)
        arme7.place(x=630, y=620)
        arme8 = Button(frameBase, text="{0}".format(liste_armes[7].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[7].id), font=font, height=1, width=16)
        arme8.place(x=630, y=670)
        arme9 = Button(frameBase, text="{0}".format(liste_armes[8].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[8].id), font=font, height=1, width=16)
        arme9.place(x=830, y=620)
        arme10 = Button(frameBase, text="{0}".format(liste_armes[9].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[9].id), font=font, height=1, width=16)
        arme10.place(x=830, y=670)
        arme11 = Button(frameBase, text="{0}".format(liste_armes[10].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[10].id), font=font, height=1, width=16)
        arme11.place(x=1030, y=620)
        arme12 = Button(frameBase, text="{0}".format(liste_armes[11].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[11].id), font=font, height=1, width=16)
        arme12.place(x=1030, y=670)
        arme13 = Button(frameBase, text="{0}".format(liste_armes[12].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[12].id), font=font, height=1, width=16)
        arme13.place(x=30, y=570)
        arme14 = Button(frameBase, text="{0}".format(liste_armes[13].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[13].id), font=font, height=1, width=16)
        arme14.place(x=230, y=570)
        arme15 = Button(frameBase, text="{0}".format(liste_armes[14].nom), borderwidth=1, activebackground="#80ad72", bg="#80ad72", command=lambda: equiper_arme(user, liste_armes[14].id), font=font, height=1, width=16)
        arme15.place(x=430, y=570)

    frameBase.mainloop()
